cisco-open/pymultiworld

README.md

contributors' pictures are added in README.md

chore: contributors in README.md

---

multiworld/world_manager.py

Ensure the termination of main thread by explicitly calling os._exit(0).

misc: explicit exit

---

README.md
examples/single_world.py

Explanation on faulty situation is added.

doc: revise readme

---

README.md

Updated docs with prerequisites.

---

multiworld/world_manager.py

Unnecessary explanation is removed from the code.

chore: clean up unnecessary text

---

.github/workflows/pypi_release.yml

pypi publishing workflow has been revised. We revise it based on
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows.

misc: pypi workflow update

---

multiworld/version.py

The version is bumped up to 0.0.2.

misc: v0.0.2

---

multiworld/version.py
patch/pytorch-v2.2.1.patch

Some files were not patched in the previous PR. This causes errors when other parts of torch.distributed are loaded. We handle the issues with the additional patch.

patch: pytorch patch revision for multiworld

---

LICENSE

The short version is replaced by a full Apache 2.0 license text.

misc: Apache 2.0 license update

---

examples/multiworld_asyncio.py
multiworld/world_communicator.py

broadcast, all-reduce, reduce, all-gather, gather and scatter are now implemented.
Also, send and recv code is simplified.

feat: support for more ccl operations

---

multiworld/version.py

The version is now set to v0.0.4.

release: version bump-up to 0.0.4

---

README.md
examples/multiworld_asyncio.py

Added world related args as dict in order to
remove confusion about the usage of this example.

refactor: update asyncio example

---

examples/resnet_multiworld.py

resnet example code is reformatted by running black

misc: reformatting resnet example

---

examples/multiworld_asyncio.py
examples/resnet_multiworld.py
multiworld/world_communicator.py

To make collective operations' signatures consistent with torch's, our signatures are restructured.

refactor: update collective operations' signatures

---

README.md

the info on the arxiv paper on MultiWorld is added in the README.md.

doc: update publication

---

examples/multiworld_all_reduce.py

all_reduce is called with SUM on each tensor for each rank within a world
after the all_reduce is called, each tensor from each rank should have the same value

feat: added multiworld all_reduce example

---

examples/all_gather/m8d.py

added all_gather example for a single world

feat: added all_gather example

---

examples/send_recv/m8d.py

This code change allows to specify rank 0 flexibly, meaning that a process belonging to more than one world can be a worker in one world and a leader in another world.

misc: make m8d-send-recv script flexible

---

examples/all_gather/README.md

added explanation on how All Gather example can be run across single and multiple worlds.

feat: added all_gather docs

---

examples/all_gather/m8d.py

feat: added all_gather example for multiple worlds

---

examples/README.md

added info about all_gather in the examples readme file

feat: updating examples readme file

---

multiworld/patch/pytorch-v2.4.0.patch
pyproject.toml

Patch file to support multiworld in pytorch v2.4.0 is created.

feat: pytorch v2.4.0 patch

---

examples/README.md
examples/broadcast/README.md

created doc for broadcast example
updated examples readme file with broadcast example

doc: added doc for broadcast

---

examples/reduce/m8d.py

implemented reduce operator example for single and multiple world

feat: added reduce example

---

examples/README.md
examples/reduce/README.md

created readme file with steps to run the reduce example

doc: added doc for reduce example

---

multiworld/version.py

PyPi complains that the file name is already taken. As an attempt to resolve the issue, we bump up the version from 0.1.0 to 0.1.1.

misc: version 0.1.1

---

multiworld/version.py

The version is bumped up to v0.1.2.

misc: version to 0.1.2

---

examples/resnet/README.md

added resnet documentation and script usage

docs: resnet documentation

---

multiworld/world_communicator.py
multiworld/world_manager.py

added more details on docstring of methods

refactor: improved docstring on methods

---

multiworld/world_communicator.py

The docstring on WorldCommunicator class is misleading. The docstring was revised.

misc: minor update on docstring

---

examples/broadcast/m8d.py
examples/reduce/m8d.py

fixed tensors on broadcast and reduce examples

fix: fixed tensors

---

docs/source/_static/multiworld.css
docs/source/conf.py
docs/source/sections/examples/all_gather.rst
docs/source/sections/examples/all_reduce.rst
docs/source/sections/examples/broadcast.rst
docs/source/sections/examples/gather.rst
docs/source/sections/examples/reduce.rst
docs/source/sections/examples/scatter.rst

updated rst files with updated README.md files
added support for images
added multiworld.css file for styiling the layout

docs: updated rst files with updated README

---

docs/source/sections/installation.rst

added installation doc with steps to install mutliworld and apply patch

docs: installation doc

---

.readthedocs.yaml
docs/requirements.txt

added .readthedocs.yaml configuration file
added requirements.txt file.

chore: added required files for RTD

---

docs/source/sections/getting_started.rst

added content on getting started rst file

docs: getting started section

---

.readthedocs.yaml

based on readthedocs documentation, current and only supported version is 2

fix: fix readthedocs build

---

docs/requirements.txt

added correct packages in the requirements file

fix: fix requirements for Sphinx build

---

multiworld/world_communicator.py
multiworld/world_manager.py

gloo backend doesn't work with isend/irecv (asynchronous point-to-point ops). See https://github.com/pytorch/pytorch/issues/30723. To mitigate the issue, we use a blocking version (send/recv) for gloo.

fix: gloo backend

---

docs/source/conf.py

added torch to autodoc mock import

fix: added mock import

---

multiworld/version.py

Version is bumped up to 0.2.0.

misc: version 0.2.0

---

docs/source/sections/ApiDocs/world_communicator.rst
docs/source/sections/ApiDocs/world_manager.rst

updated API docs with new modules names

docs: updated API docs

---

docs/source/sections/getting_started.rst
docs/source/sections/installation.rst

Now that the post-installation setup is automated, the installation-related docs are updated.

docs: revise description on installation

---

multiworld/version.py

misc: version 0.2.1

---

CODE_OF_CONDUCT.md
multiworld/communicator.py
pyproject.toml

The maintainers' email address is correctly updated. A debugging message was removed since it can be annoying when the function of checking a world's status is called frequently.

chore: miscellaneous update

---

multiworld/version.py

misc: version 0.2.2
